version: "3"
services:
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        env_name: prod
        app_name: app
    ports:
      - "80:80"
    image: 150909075967.dkr.ecr.eu-central-1.amazonaws.com/pandazapi-prod/app:latest
